#! /usr/bin/env python

# This script takes student submissions using 'submit'                          
# and expands them into a directory for grading.                                
#                                                                               
# by Mark Sherman, msherman@cs.uml.edu  
#
# r2012.04.06   - It not longer tries to update permissions on feedback.txt* files
#               - (this could be extended to a list of no-touchie files)
#
# r2012.02.22   - broke out file permission change to its own function.
#               - Now sets user as owner of files, too (experimental)
#
# r0            - initial release                                        

import os
import grp
import shutil
import stat
import glob
import getopt
import sys
import re

# ROOTs are within HOMEDIR
HOMEDIR = '/usr/cs/grad/doc/msherman/'
SRCROOT = 'submit/101'
DSTROOT = 'grading/101'
SKELROOT = 'grading/101/skel'
GROUP = '91101ta'

# Make directories more convenient for use
SRC = HOMEDIR + SRCROOT + '/'
DST = HOMEDIR + DSTROOT + '/'
SKEL = HOMEDIR + SKELROOT + '/'
GID = grp.getgrnam(GROUP).gr_gid
UID = os.getuid()
MOD = stat.S_IRWXU | stat.S_IRWXG

# Process arguments
# a : assignment name
# s : student username
opts, args = getopt.getopt(sys.argv[1:], 'a:s:')
assignment = student = ''
for o, x in opts:
    if o == '-a':
        assignment = x
    elif o == '-s':
        student = x
    else:
        assert False, "unhandled option " + o

def setPermissions(anyfile):
    os.chown( anyfile , UID , GID)
    os.chmod( anyfile, MOD )

# Takes the specified student/assignment and extracts it
def getFile(assignment, student):
    srcfile = SRC + assignment + '/' + student + '.tar'
    # Make sure source file exists
    if os.access(srcfile , os.F_OK):
        print 'Found ' + srcfile
    else:
        print 'File does not exist, exiting.'
        return
    
    # Creates the directory to expand files into
    # Will create directory if it doesn't exist
    curdir = DST + assignment
    if not os.access( curdir , os.F_OK):
        print 'Making directory ' + curdir
        os.mkdir( curdir )
        setPermissions( curdir )
    
    curdir = curdir + '/' + student
    if not os.access( curdir , os.F_OK ):
        os.mkdir( curdir )
        setPermissions( curdir )
        
    # Folder is now ready, expand files into it
    os.chdir(curdir)
    os.system('tar -xpf ' + srcfile)
    
    # Add extra files from the skel directory.
    # Useful for test data and scripts
    if os.access( SKEL + assignment , os.F_OK):
        line = 'cp -a ' + SKEL + assignment + '/* .'
        os.system(line)
    
    # Update group and file mode.
    # files = glob.glob('*')
    #     for x in files:
    #         if not re.match("feedback.txt", x):
    #             setPermissions( x )
    # 
    
# Do the things
if assignment == '' and student == '':
    print "Nothing specified"

elif assignment != '' and student != '':
    print 'Getting individual ' + assignment + ' ' + student
    getFile(assignment, student)
    
elif assignment != '' and student == '':
    print 'Getting assignment ' + assignment
    os.chdir(SRC + assignment)
    for x in glob.glob('*.tar'):
        getFile( assignment, x[:len(x)-4] )

else:
    print 'Not sure what to do. Exiting.'